title:              O teu jornal
email:              oteujornal@gmail.com
description:        Jornal da Escola Secundária de Vilela, Paredes, Portugal
author:             Alunos da Escola Secundária de Vilela
baseurl:            "/"
url:                "https://oteujornal.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    oteujornal
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
